name: Publish Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      # Build RadiantPi.Sony.Cledis
      - name: Restore dependencies
        run: dotnet restore Source/RadiantPi.Sony.Cledis/RadiantPi.Sony.Cledis.csproj
      - name: Build
        run: dotnet build --no-restore Source/RadiantPi.Sony.Cledis/RadiantPi.Sony.Cledis.csproj

      # Build Samples
      - name: Build Show Module Temperatures Sample
        run: dotnet build Samples/ShowModuleTemperatures/ShowModuleTemperatures.csproj

      - name: Build Show Status
        run: dotnet build Samples/ShowStatus/ShowStatus.csproj

      # Publish RadiantPi.Sony.Cledis
      - name: Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
            PROJECT_FILE_PATH: Source/RadiantPi.Sony.Cledis/RadiantPi.Sony.Cledis.csproj
            NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
